# Generated by Django 4.2.3 on 2024-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
