# Generated by Django 5.2.7 on 2025-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('entertainment', 'Entertainment'), ('news', 'News'), ('education', 'Education'), ('tech', 'Tech'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
