# Generated by Django 5.2.7 on 2025-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description for the post', max_length=160),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
